buggy_race_server/race/forms.py
# -*- coding: utf-8 -*-
"""Race forms."""

from flask_wtf import FlaskForm
from wtforms import (
    BooleanField,
    DateTimeField,
    FileField,
    HiddenField,
    IntegerField,
    StringField,
    TextAreaField,
)
from wtforms.validators import Length, NumberRange, Optional, ValidationError

from buggy_race_server.race.models import Race
from buggy_race_server.config import ConfigSettings

class RaceForm(FlaskForm):
    """Race form."""
    id = HiddenField()

    title = StringField(
        "Title", validators=[Optional(), Length(max=ConfigSettings.MAX_RACE_TITLE_LENGTH)]
    )
    desc = TextAreaField(
        "Description", validators=[Optional(), Length(max=ConfigSettings.MAX_RACE_DESC_LENGTH)]
    )
    cost_limit = IntegerField(
        "Cost limit",
        validators=[
            Optional(),
            NumberRange(
                min=ConfigSettings.MIN_RACE_COST_LIMIT,
                max=None
            )
        ]
    )
    start_at = DateTimeField(
        "Race start time",
        format='%Y-%m-%dT%H:%M', # note: T is important!
        validators=[Optional()]
    )
    is_visible = BooleanField("Is visible?")
    is_result_visible = BooleanField("Are results visible?")
    results_uploaded_at = DateTimeField(
        "Results uploaded at",
        format='%Y-%m-%dT%H:%M', # note: T is important!
        validators=[Optional()]
    )
    is_abandoned = BooleanField("Is abandoned?")
    race_file_url = StringField(
        "URL of results JSON", validators=[Optional(), Length(max=ConfigSettings.MAX_URL_LENGTH)]
    )
    track_image_url = StringField(
        "URL of racetrack image", validators=[Optional(), Length(max=ConfigSettings.MAX_URL_LENGTH)]
    )
    track_svg_url = StringField(
        "URL of path SVG", validators=[Optional(), Length(max=ConfigSettings.MAX_URL_LENGTH)]
    )
    max_laps = IntegerField(
        "Number of laps",
        validators=[Optional(), NumberRange(min=0, max=None)]
    )
    lap_length = IntegerField(
        "Lap length",
        validators=[Optional(), NumberRange(min=0, max=None)]
    )
    svg_path_length = IntegerField(
        "SVG path length",
        validators=[Optional(), NumberRange(min=0, max=None)]
    )
    is_dnf_position = BooleanField("Is Did-Not-Finish a position?")
    
    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RaceForm, self).__init__(*args, **kwargs)
        self.race = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RaceForm, self).validate()
        is_valid = True
        if not initial_validation:
            return False
        if self.start_at.data is None:
            self.start_at.data = Race.get_default_race_time()
        race_at_this_time = Race.query.filter_by(start_at=self.start_at.data).first()
        if race_at_this_time and self.id.data != str(race_at_this_time.id):
            self.start_at.errors.append("Already got a race starting at this time")
            is_valid = False
        dup_fields = Race.get_duplicate_urls(
            self.id.data, self.race_file_url.data)
        if dup_fields:
            if "race_file_url" in dup_fields:
                self.race_file_url.errors.append(f"Already got a race with that result log URL (must be unique)")
            is_valid = False
        return is_valid


class RaceDeleteForm(FlaskForm):
    is_confirmed = BooleanField("Are you sure?")
  
    def __init__(self, *args, **kwargs):
        super(RaceDeleteForm, self).__init__(*args, **kwargs)
  
    def validate(self):
        return super(RaceDeleteForm, self).validate()


class RaceResultsForm(FlaskForm):
    results_json_file = FileField("JSON results file")
    is_ignoring_warnings = BooleanField("Ignore warnings?")
    is_overwriting_urls = BooleanField("Use URLs found inside JSON?")

    def __init__(self, *args, **kwargs):
        super(RaceResultsForm, self).__init__(*args, **kwargs)

    def validate(self):
        return super(RaceResultsForm, self).validate()

class RacetrackForm(FlaskForm):
    title = StringField(
        "Title", validators=[Optional(), Length(max=ConfigSettings.MAX_RACE_TITLE_LENGTH)]
    )
    desc = TextAreaField(
        "Description", validators=[Optional(), Length(max=ConfigSettings.MAX_RACE_DESC_LENGTH)]
    )
    track_image_url = StringField(
        "URL of racetrack image", validators=[Optional(), Length(max=ConfigSettings.MAX_URL_LENGTH)]
    )
    track_image_file = FileField(
        "Custom racetrack image", validators=[Optional()]
    )
    # allow form to specifiy _removal_ of (existing) image data
    is_deleting_track_image_file = BooleanField(
        "Delete racetrack image?",
        default=False,
        render_kw ={'checked':''},
        validators=[Optional()]
    )
    track_svg_url = StringField(
        "URL of path SVG", validators=[Optional(), Length(max=ConfigSettings.MAX_URL_LENGTH)]
    )
    track_svg_file = FileField(
        "Custom racetrack path SVG", validators=[Optional()]
    )
    # allow form to specifiy _removal_ of (existing) SVG
    is_deleting_track_svg = BooleanField(
        "Delete custom SVG?", validators=[Optional()]
    )
    lap_length = IntegerField(
        "Lap length",
        validators=[Optional(), NumberRange(min=0, max=None)]
    )
    svg_path_length = IntegerField(
        "SVG path length",
        validators=[Optional(), NumberRange(min=0, max=None)]
    )

buggy_race_server/race/__init__.py
# -*- coding: utf-8 -*-
"""The race module."""
from . import views, models  # noqa

buggy_race_server/race/views.py
# -*- coding: utf-8 -*-
"""Race views."""

import json
from datetime import datetime, timezone
import os
import re
from sqlalchemy import insert, and_, or_
from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from flask_login import current_user, login_required
from buggy_race_server.admin.forms import GeneralSubmitForm, SubmitWithConfirmForm
from buggy_race_server.admin.models import DbFile
from buggy_race_server.database import db
from buggy_race_server.race.forms import RaceForm, RaceDeleteForm, RaceResultsForm, RacetrackForm
from buggy_race_server.race.models import Race, RaceResult, Racetrack
from buggy_race_server.user.models import User
from buggy_race_server.utils import (
    admin_only,
    cors_allow_origin,
    flash_errors,
    get_download_filename,
    get_flag_color_css_defs,
    get_temp_race_file_info,
    staff_only,
    join_to_project_root,
    servertime_str,
)
from buggy_race_server.config import ConfigSettingNames, ConfigSettings

blueprint = Blueprint("race", __name__, url_prefix="/races", static_folder="../static")

# race assets:
# Serving statically because it's more robust than trying to
# figure out how to exclude these from webpack, and even then it's
# too complex in the event of changes: keep it simple.
# Want it standalone because it's handy to be able to dev/run it
# in isolation outwith the race server, at least for now.

def _serve_race_asset_file(*args):
    full_filename = join_to_project_root(*args)
    if not os.path.exists(full_filename):
        # don't send full error page, as responses generally aren't
        # being seen by human user, but as a component on a page
        print(f"Race resource not found <{full_filename}>")
        return make_response(f"Race resource not found <{full_filename}>", 404)
    return send_file(full_filename)

@blueprint.route("/assets/track/<int:track_id>/img")
@cors_allow_origin
def serve_racetrack_custom_image(track_id):
    track = Racetrack.get_by_id(track_id)
    if track is None:
        abort(404)
    if track.track_image is None or len(track.track_image) == 0 or not track.image_media_type:
        flash("No custom image associated with this track", "danger")
        abort(404)
    ext = re.sub(r'.*/', "", track.image_media_type)
    response = make_response(track.track_image)
    response.headers["Content-type"] = track.image_media_type
    response.headers["Content-disposition"] = f"attachment; filename=racetrack-{track_id}.{ext}"
    response.headers["Content-length"] = len(track.track_image)
    return response

@blueprint.route("/assets/track/<int:track_id>/svg")
@cors_allow_origin
def serve_racetrack_custom_svg(track_id):
    track = Racetrack.get_by_id(track_id)
    if track is None:
        abort(404)
    if track.track_svg is None or len(track.track_svg) == 0:
        flash("No custom SVG path associated with this track", "danger")
        abort(404)
    response = make_response(track.track_svg)
    response.headers["Content-type"] = "image/svg+xml; charset=utf-8"
    response.headers["Content-disposition"] = f"attachment; filename=racetrack-{track_id}.svg"
    response.headers["Content-length"] = len(track.track_svg)
    return response

@blueprint.route("/assets/tracks/<filename>")
@cors_allow_origin
def serve_racetrack_asset(filename):
    return _serve_race_asset_file(
        current_app.config[ConfigSettingNames._RACE_ASSETS_RACETRACK_PATH.name],
        filename
    )

@blueprint.route("/assets/img/<filename>")
@cors_allow_origin
def serve_race_player_image(filename):
    return _serve_race_asset_file(
        current_app.config[ConfigSettingNames._RACE_ASSETS_IMAGES_PATH.name],
        filename
    )

@blueprint.route("/assets/<filename>")
def serve_race_player_asset(filename):
    return _serve_race_asset_file(
        current_app.config[ConfigSettingNames._RACE_ASSETS_PATH.name],
        filename
    )

@blueprint.route("/", strict_slashes=False)
def show_public_races():
    """Race announcement page."""
    next_race=Race.query.filter(
        Race.is_visible==True,
        Race.start_at > datetime.now(timezone.utc)
      ).order_by(Race.start_at.asc()).first()
    races = db.session.query(Race).outerjoin(RaceResult).filter(
            Race.is_visible==True,
            Race.start_at < datetime.now(timezone.utc),
            or_(
                Race.is_abandoned==True,
                and_(
                    RaceResult.race_position > 0,
                    RaceResult.race_position <= 3
                )
            )
        ).order_by(Race.start_at.desc()).all()
    results = [ race.results for race in races ]
    flag_color_css_defs = get_flag_color_css_defs(
        [result for sublist in results for result in sublist]
    )
    return render_template(
        "races/index.html",
        flag_color_css_defs=flag_color_css_defs,
        next_race=next_race,
        races=races,
        replay_anchor=Race.get_replay_anchor(),
    )

@blueprint.route("races.json", strict_slashes=True)
@cors_allow_origin
def serve_races_json():
    filename = get_download_filename("races.json", want_datestamp=True)
    races=Race.query.filter(
        Race.is_visible==True,
        Race.start_at < datetime.now(timezone.utc)
      ).order_by(Race.start_at.asc())
    races_list = [
        {
            "id": race.id,
            "title": race.title,
            "start_at": servertime_str(
                current_app.config[ConfigSettingNames.BUGGY_RACE_SERVER_TIMEZONE.name],
                race.start_at
            ),
            "race_file_url": race.race_file_url if (
                race.is_result_visible and not race.is_abandoned
            ) else None,
            "is_abandoned": race.is_abandoned if race.is_result_visible else None
        }
        for race in races
    ]
    json_data = json.dumps(races_list, indent=1, separators=(',', ': '))
    output = make_response(json_data, 200)
    output.headers["Content-Disposition"] = f"attachment; filename={filename}"
    output.headers["Content-type"] = "application/json"
    output.headers["Content-length"] = len(json_data)
    return output

@blueprint.route("/<int:race_id>/replay")
def replay_race(race_id):
    race = Race.query.filter_by(id=race_id).first_or_404()
    if not (race.is_visible and race.is_result_visible):
        if current_user.is_anonymous or not current_user.is_staff:
            flash("The results of this race are not available yet", "warning")
            abort(403)
    if race.is_abandoned:
        flash("Race was abandoned: nothing to replay", "warning")
        abort(404)
    race_file_url = race.race_file_url
    if race_file_url and not (re.match(r"^https?://", race_file_url)):
        race_file_url = url_for(
            "race.serve_race_player_asset",
            filename=race_file_url
        )
    if player_url := current_app.config[ConfigSettingNames.BUGGY_RACE_PLAYER_URL.name]:
        anchor = Race.get_replay_anchor()
        return redirect(f"{player_url}?race={race_file_url}{anchor}")
    if current_user.is_anonymous:
        current_user_username = "nobody!" # ensure no username match with "!"
    else:
        current_user_username = current_user.username
    return render_template(
        "races/player.html",
        current_user_username=current_user_username,
        cachebuster=current_app.config[ConfigSettings.CACHEBUSTER_KEY],
        race_file_url=race_file_url,
    )

@blueprint.route("/<int:race_id>/result")
def show_race_results(race_id):
    race = Race.query.filter_by(id=race_id).first_or_404()

    if is_preview := not (race.is_visible and race.is_result_visible):
        if current_user.is_anonymous or not current_user.is_staff:
            flash("Results for this race are not available yet", "danger")
            flash("Either the results haven't been uploaded, or they haven't been published yet (maybe try again later?)", "info")
            abort(404)
        else:
            flash("Results for this race have not been published yet: you're seeing this preview because you're staff", "warning")

    all_results = db.session.query(
        RaceResult, User).outerjoin(User).filter(
            RaceResult.race_id==race.id
        ).order_by(RaceResult.race_position.asc()).all() 

    results_finishers = [(res, user)  for (res, user) in all_results if res.race_position > 0 ]
    results_nonfinishers = [(res, user) for (res, user) in all_results if res.race_position == 0 ]
    results_disqualified = [(res, user) for (res, user) in all_results if res.race_position < 0 ]
    is_tied = {}
    prev_pos = 0
    for (res, _) in results_finishers:
        if res.race_position == prev_pos:
            is_tied[prev_pos] = "="
        prev_pos = res.race_position
    flag_color_css_defs = get_flag_color_css_defs([res for (res, _) in all_results])
    return render_template(
        "races/result.html",
        is_preview=is_preview,
        current_user_id=0 if current_user.is_anonymous else current_user.id,
        flag_color_css_defs=flag_color_css_defs,
        is_showing_usernames=current_app.config[ConfigSettingNames.IS_USERNAME_PUBLIC_IN_RESULTS.name],
        is_tied=is_tied,
        race=race,
        replay_anchor=Race.get_replay_anchor(),
        results=all_results,
        results_disqualified=results_disqualified,
        results_finishers=results_finishers,
        results_nonfinishers=results_nonfinishers,
    )

@blueprint.route("/<int:race_id>/race-file.json")
@blueprint.route("/<int:race_id>/race-file")
@cors_allow_origin
def serve_race_file(race_id):
    race = Race.query.filter_by(id=race_id).first_or_404()
    if not (race.is_visible and race.is_result_visible):
        if current_user.is_anonymous or not current_user.is_staff:
            flash("Race file not available yet", "danger")
            abort(403)
    if race.is_abandoned: # don't show race file

buggy_race_server/templates/races/_results.html
{% if race.is_abandoned %}
  <div class="row">
    <div class="col">
      <div class="alert alert-info p-3">
        This race was abandoned.
      </div>
    </div>
  </div>
{% elif race.results_uploaded_at or all_results|count %}
  <div class="row">
    <div class="col-md-6 my-3">
      <h3>Raced</h3>
      <table class="table table-striped table-bordered table-hover bg-white">
        <tr>
          <th class="text-center">Position</th>
          <th>Buggy</th>
          <th>Racer</th>
          <th>Cost</th>
        </tr>
        {% if race.buggies_started == 0 %}
          <tr>
            <td colspan="4" class="text-center">
              <em>No buggies started the race!</em>
            </td>
          </tr>
        {% else %}
          {% for (res, user) in results_finishers %}
            <tr>
              <td class="text-center">
                <strong>
                  {{ is_tied[res.race_position] }}{{ res.race_position }}
                </strong>
              </td>
              <td>
                <div class="flag {{ flag_color_css_defs[res.flag_color_secondary][0] }}"
                ><div class="flag-{{ res.flag_pattern }} {{ flag_color_css_defs[res.flag_color][0] }}">&nbsp;</div></div>
              </td>
              <td {% if user.id == current_user_id %}class="alert-info"{% endif %}>
                {% if is_showing_usernames %}
                  {{ user.pretty_username }}
                {% elif user.id == current_user_id %}
                  <em>Your buggy!</em>
                {% endif %}
              </td>
              <td>
                {{ res.cost }}
              </td>
            </tr>
          {% else %}
            <tr>
              <td class="alert-danger" colspan="4">
                <em>No buggies crossed the finishing line</em>
              </td>
            </tr>
          {% endfor %}
          {% for (res, user) in results_nonfinishers %}
            <tr>
              <td class="text-center">
                &mdash;
              </td>
              <td>
                <div class="flag {{ flag_color_css_defs[res.flag_color_secondary][0] }}"
                ><div class="flag-{{ res.flag_pattern }} {{ flag_color_css_defs[res.flag_color][0] }}">&nbsp;</div></div>
            </td>
              <td {% if user.id == current_user_id %}class="alert-info"{% endif %}>
                {% if is_showing_usernames %}
                  {{ user.pretty_username }}
                {% elif user.id == current_user_id %}
                  <em>Your buggy!</em>
                {% endif %}
              </td>
              <td>
                {{ res.cost }}
              </td>
            </tr>
          {% endfor %}
        {% endif %}
      </table>
    </div>
    <div class="col-md-6 my-3">
      <h3>Did not qualify</h3>
      <table class="table table-striped table-bordered table-hover bg-white">
        <tr>
          <th>Buggy</th>
          <th>Racer</th>
          <th>Violations</th>
          <th>Cost</th>
        </tr>
        {% for (res, user) in results_disqualified %}
          <tr>
            <td>
              <div class="flag {{ flag_color_css_defs[res.flag_color_secondary][0] }}"
              ><div class="flag-{{ res.flag_pattern }} {{ flag_color_css_defs[res.flag_color][0] }}">&nbsp;</div></div>
            </td>
            <td {% if user.id == current_user_id %}class="alert-info"{% endif %}>
              {% if is_showing_usernames %}
                {{ user.pretty_username }}
              {% elif user.id == current_user_id %}
                <em>Your buggy!</em>
              {% endif %}
            </td>
          <td>
              <ul class="sm-item-list">
              {% for v in res.violations_str.split(',') %}
                <li><span class="sm-item rule-violation">{{ v }}</span></li>
              {% endfor %}
              </ul>
            </td>
            <td>
              {{ res.cost }}
            </td>
          </tr>
        {% else %}
          <tr>
            <td class="text-center" colspan="4">
              <em>No buggies were disqualified</em>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% else %}
  {# There's no results_uploaded_at and all_results is empty. This may be     #}
  {# because the race has been abandoned, in which case this section isn't    #}
  {# displayed.                                                               #}
  <div class="row">
    <div class="col">
      <div class="alert alert-info p-3">
        No results have been uploaded for this race.
      </div>
    </div>
  </div>
{% endif %}

buggy_race_server/templates/races/index.html
{% extends "layout.html" %}
{% block page_title %} Buggy races {% endblock %}
{% block content %}
<div class="container pb-5">
  <div class="row">
    <h1 class="col my-3">Next buggy race</h1>
  </div>
  {% if next_race %}
    <div class="row">
      <div class="col">
        <div class="w-100 buggy-stripes">&nbsp;</div>
        <div class="alert alert-info text-center">
          <h4>
            {% if next_race.title %}
              <strong>{{ next_race.title }}</strong>
            {% else %}
              <strong>Next Race</strong>
            {% endif %}
          </h4>
          {% if next_race.desc %}
            <div class="m-3">
              {{ next_race.desc|safe }}
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="alert alert-success text-center">
          <h2 class="m-3">
            {{ next_race.start_at_servertime.strftime('%A') }}
            <br>
            {{ next_race.start_at_servertime.strftime('%Y-%m-%d') }}
            <br>
            {{ next_race.start_at_servertime.strftime('%H:%M') }}
            </strong>
          </h2>
        </div>
      </div>
      <div class="col-md-6">
        <div class="alert alert-danger text-center">
          <h2 class="m-3">
            <strong>
              Cost limit<br>
              <span style="font-size:200%">{{ next_race.cost_limit }}</span>
            </strong>
            </h2>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <div class="alert alert-warning text-center">
          <p class="m-3">
            Make sure you've uploaded a buggy with a total cost less than or
            equal to {{ next_race.cost_limit }} <em>before</em> the race starts.
          </p>
        </div>
      </div>
    </div>  
  {% else %}
    <div class="row">
      <div class="alert alert-warning w-100 text-center">
        <p class="m-3"><strong>Next race not yet announced.</strong></p>
      </div>
    </div>
  {% endif %}  
</div>

<div class="container pb-5">
  <div class="row">
    <h1 class="col my-3">Previous race results</h1>
  </div>  
  {% if races|length == 0 %}
    <div class="alert alert-warning w-100 text-center">
      <p class="m-3"><strong>No race results are available yet.</strong></p>
    </div>
  {% else %}
    <div class="row">
      <table class="col table table-striped table-bordered table-hover table-responsive bg-white">
        <thead>
          <tr>
            <th><span class="icon-trophy"></span></th>
            <th class="text-center">1</th>
            <th class="text-center">2</th>
            <th class="text-center">3</th>
            <th>Race time</th>
            <th>Cost limit</th>
            <th class="text-col">Title & details</th>
          </tr>
        </thead>
        <tbody>
            {% for race in races %}
              <tr class="race-visible-{{ race.is_visible }}">
                {% if not race.is_result_visible %}
                  <td colspan="4" class="text-center">
                    <em>Awaiting race report</em>
                  </td>
                {% elif race.results_uploaded_at %}
                  <td class="btn-collection">
                    {% if race.results_uploaded_at %}
                      <a class="btn btn-outline-secondary btn-white btn-jump"
                      href="{{ url_for('race.show_race_results', race_id=race.id) }}">Results</a>
                    {% endif %}
                    {% if race.race_file_url %}
                      <a class="btn btn-outline-secondary btn-white btn-jump" href="{{ url_for('race.replay_race', race_id=race.id) }}{{ replay_anchor }}">Replay</a>
                    {% endif %}
                  </td>
                  <td>
                    {% for res in race.results if res.race_position == 1 %}
                      <div class="flag {{ flag_color_css_defs[res.flag_color_secondary][0] }}"
                       ><div class="flag-{{ res.flag_pattern }} {{ flag_color_css_defs[res.flag_color][0] }}">&nbsp;</div></div>
                    {% else %}
                      <div class="flag no-buggy"></div>
                    {% endfor %}
                  </td>
                  <td>
                    {% for res in race.results if res.race_position == 2 %}
                      <div class="flag {{ flag_color_css_defs[res.flag_color_secondary][0] }}"
                        ><div class="flag-{{ res.flag_pattern }} {{ flag_color_css_defs[res.flag_color][0] }}">&nbsp;</div></div>
                    {% else %}
                      <div class="flag no-buggy"></div>
                    {% endfor %}
                  </td>
                  <td>
                    {% for res in race.results if res.race_position == 3 %}
                      <div class="flag {{ flag_color_css_defs[res.flag_color_secondary][0] }}"
                        ><div class="flag-{{ res.flag_pattern }} {{ flag_color_css_defs[res.flag_color][0] }}">&nbsp;</div></div>
                    {% else %}
                      <div class="flag no-buggy"></div>
                    {% endfor %}
                  </td>
                {% else %}
                  <td colspan="4" class="text-center">
                    {% if race.is_abandoned %}
                      <em>Race abandoned</em>
                    {% else %}
                      <em>Awaiting race report</em>
                    {% endif %}
                  </td>
                {% endif %}
                <td>
                  {{ race.start_at | servertime }}
                </td>
                <td class="text-center">
                  {{ race.cost_limit }}
                </td>
                <td>
                  <div class="cell-title">
                    {% if race.title %}<strong>{{ race.title }}</strong>{% else %}<em>Untitled</em>{% endif %}
                  </div>
                  {% if race.desc %}
                    <div class="my-2 race-desc">{{ race.desc }}</div>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
  <div class="row">
    <div class="col">
      <p class="btn-collection text-right">
        <a class="btn btn-sm btn-outline-secondary btn-white btn-download" href="{{ url_for('race.serve_races_json') }}">Races JSON</a>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col text-center">
      <img class="img-fluid" src="{{ static_url_for('static', filename='build/img/rene-buggy-1.png') }}" />
    </div>
  </div>
</div>

{% endblock %}

buggy_race_server/templates/races/player.html
{% extends "layout.html" %}
{% block page_title %}Race replay{% endblock %}
{% block body_class %}race-player{% endblock %}
{% block content %}
{% include "races/_player.html" %}
{% endblock %}

buggy_race_server/templates/races/player_stripped_down.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Race replay</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- minimal Buggy Racing project race-player: https://www.buggyrace.net -->
</head>
<body class="race-player">
  {% include "races/_player.html" %}
</body>
</html>

buggy_race_server/templates/races/result.html
{% extends "layout.html" %}
{% block page_title %} Race result {{ race.title }} {% endblock %}
{% block content %}
<div class="container pb-3">
  <div class="row">
    <div class="d-flex align-items-start w-100">
      <div class="col">
        <div class="my-3 border text-center">
          <div class="w-100 finish-chequers" style="height:4em">&nbsp;</div>
          {% if is_preview %}
            <div class="alert alert-warning">
              <h2 class="alert-title">Result preview</h2>
              <p>
                This is a preview of the results page. To make it public, you'll
                need to <a href="{{ url_for( 'admin_race.edit_race', race_id=race.id) }}">edit
                the race</a> and set "Is visible?" and "Are results visible?"
                to <code>Yes</code>.
              </p>
            </div>
          {% endif %}
          <h1 class="mt-3">
            Race result
            {% if race.title %}
              for <em>{{ race.title }}</em>
            {% endif %}
          </h4>
          {% if race.desc %}
            <div class="m-3">
              {{ race.desc|safe }}
            </div>
          {% endif %}
          {% if race.race_file_url %}
            <div class="m-3">
              <a class="btn btn-outline-secondary btn-white btn-jump" href="{{ url_for('race.replay_race', race_id=race.id) }}{{ replay_anchor }}">Replay</a>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="d-flex align-items-start w-100">
      <div class="col">
        <div class="alert alert-secondary text-center">
          <h2 class="m-3">
            <strong>
            {{ race.start_at_servertime.strftime('%A') }}
            <br>
            {{ race.start_at_servertime.strftime('%Y-%m-%d') }}
            <br>
            {{ race.start_at_servertime.strftime('%H:%M') }}
            </strong>
          </h2>
        </div>
      </div>
      <div class="col">
        <div class="alert alert-danger text-center">
          <h2 class="m-3">
            <strong>
              Cost limit<br>
              <span style="font-size:200%">{{ race.cost_limit }}</span>
            </strong>
            </h2>
        </div>
      </div>
    </div>
  </div>

  {% include "races/_results.html" %}

</div>

{% endblock %}