buggy_race_server/api/views.py
# -*- coding: utf-8 -*-
"""API views."""

import json
from datetime import datetime, timezone, timedelta

from flask import Blueprint, Response, request, current_app, render_template, after_this_request

from buggy_race_server.buggy.forms import BuggyJsonForm
from buggy_race_server.buggy.views import handle_uploaded_json
from buggy_race_server.user.models import User
from buggy_race_server.config import ConfigSettingNames
from buggy_race_server.admin.views import get_admin_dashboard_data_response

blueprint = Blueprint("api", __name__, url_prefix="/api", static_folder="../static")

API_SECRET_LIFESPAN_MINS = 60

API_KEY_USER = "user"
API_KEY_KEY = "key" # API key for the API key, heh
API_KEY_SECRET = "secret"
API_KEY_JSON = "buggy_json"

def get_json_error_response(msg, status=401):
  response = Response(
    '{"error": "' + msg + '"}',
    status=status,
    mimetype="application/json"
  )
  response.headers.add("Access-Control-Allow-Origin", "*") # CORS
  return response

@blueprint.route("/", methods=["GET"], strict_slashes=False)
def describe_api():
  return render_template(
    "public/api.html",
    api_task_name=current_app.config[ConfigSettingNames.TASK_NAME_FOR_API.name],
    buggy_race_server_url=current_app.config[ConfigSettingNames.BUGGY_RACE_SERVER_URL.name],
  )

def get_user_or_response_from_api_post(request):
    """ returns either"""
    username = ""
    api_key = ""
    secret = ""
    if API_KEY_USER in request.form:
        username = request.form[API_KEY_USER].strip()
    if not username:
        return get_json_error_response("missing user")
    if API_KEY_KEY in request.form:
        api_key = request.form[API_KEY_KEY].strip()
    if not api_key:
        return get_json_error_response("missing API key")
    if API_KEY_SECRET in request.form:
        secret = request.form[API_KEY_SECRET].strip()
    if not secret:
        return get_json_error_response("missing secret")
    user = User.query.filter_by(username=username).first()
    if user is None:
        return get_json_error_response("not authorised (bad user)")
    if user.api_key != api_key:
        return get_json_error_response("not authorised (wrong API key for this user)")
    if user.api_secret is None:
        return get_json_error_response("not authorised (missing secret)")
    if user.api_secret_at is None:
        return get_json_error_response("not authorised (missing secret timestamp)")
    if user.api_secret != secret:
        return get_json_error_response(f"not authorised (bad secret)")
    now_utc = datetime.now(timezone.utc)
    api_secret_at_utc = user.api_secret_at.replace(tzinfo=timezone.utc)
    try:
        delta_time_in_s = (now_utc - user.api_secret_at) / timedelta(seconds=1)
    except TypeError:
        delta_time_in_s = (now_utc - api_secret_at_utc) / timedelta(seconds=1)
    if delta_time_in_s > current_app.config[ConfigSettingNames.API_SECRET_TIME_TO_LIVE.name]:
        return get_json_error_response("not authorised (secret has expired)")
    if user.is_api_secret_otp:
        if user.api_secret_count > 0:
            return get_json_error_response("one-time secret has already been used")
        user.api_secret_count += 1
        user.save()
    return user

@blueprint.route("/upload", methods=["POST", "OPTIONS"], strict_slashes=True)
def create_buggy_with_json_via_api():
  """ API call  """
  # basic API call to /api/upload with four params:
  #        user (the username for the user whose buggy to use)
  #        key (the API key for this user)
  #        secret (must match recent secret)
  #        buggy_json
  #
  if request.method == "OPTIONS":
      # CORS preflight enquiry
      # wildcards are OK here because the API is stateless so isn't
      # handling cookies: auth is provided in the data payload
      response = Response(status=204) # 204: no content
      response.headers.add("Access-Control-Allow-Origin", "*")
      response.headers.add("Access-Control-Allow-Headers", "*")
      response.headers.add("Access-Control-Allow-Methods", "POST")
      return response
  user_or_response = get_user_or_response_from_api_post(request)
  if isinstance(user_or_response, Response):
      return user_or_response
  if not isinstance(user_or_response, User): # unexpected: should be Resonse or User
      return get_json_error_response("bad request") # didn't get a user
  user = user_or_response
  if API_KEY_JSON in request.form:
      buggy_json = request.form[API_KEY_JSON].strip()
  if not buggy_json:
      return get_json_error_response(f"no JSON ({API_KEY_JSON}) provided", status=200)
  # now send 200 even when response is an error (e.g., JSON parse fail)
  response = Response(
    json.dumps(handle_uploaded_json(BuggyJsonForm(request.form), user, True)),
    status=200,
    mimetype="application/json"
  )
  response.headers.add("Access-Control-Allow-Origin", "*") # CORS
  return response

@blueprint.route("/admin/dashboard", methods=["GET", "POST"], strict_slashes=True)
def dashboard_data_via_api():
    """ API call  """
    @after_this_request
    def add_no_cache_header(response):
        # discourage caching here
        response.headers["Vary"] = "*" # Flask also unhelpfully sets "cookie"
        response.headers["Cache-Control"] = "no-cache"
        return response
    payload = {}
    if not current_app.config[ConfigSettingNames.IS_ADMIN_API_ENABLED.name]:
        status = 404
    elif request.method != "POST":
        status = 405 # method not allowed
    else:
        user_or_response = get_user_or_response_from_api_post(request)
        if isinstance(user_or_response, Response):
            return user_or_response
        user = user_or_response
        if not user.is_administrator:
            return get_json_error_response("not authorised (user not an administrator)")
        return get_admin_dashboard_data_response(want_json=True)
    return Response(
        json.dumps(payload) if payload else None, # None results in empty body
        status=status,
        mimetype="application/json"
    )

buggy_race_server/race/views.py
# -*- coding: utf-8 -*-
"""Race views."""

import json
from datetime import datetime, timezone
import os
import re
from sqlalchemy import insert, and_, or_
from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from flask_login import current_user, login_required
from buggy_race_server.admin.forms import GeneralSubmitForm, SubmitWithConfirmForm
from buggy_race_server.admin.models import DbFile
from buggy_race_server.database import db
from buggy_race_server.race.forms import RaceForm, RaceDeleteForm, RaceResultsForm, RacetrackForm
from buggy_race_server.race.models import Race, RaceResult, Racetrack
from buggy_race_server.user.models import User
from buggy_race_server.utils import (
    admin_only,
    cors_allow_origin,
    flash_errors,
    get_download_filename,
    get_flag_color_css_defs,
    get_temp_race_file_info,
    staff_only,
    join_to_project_root,
    servertime_str,
)
from buggy_race_server.config import ConfigSettingNames, ConfigSettings

blueprint = Blueprint("race", __name__, url_prefix="/races", static_folder="../static")

# race assets:
# Serving statically because it's more robust than trying to
# figure out how to exclude these from webpack, and even then it's
# too complex in the event of changes: keep it simple.
# Want it standalone because it's handy to be able to dev/run it
# in isolation outwith the race server, at least for now.

def _serve_race_asset_file(*args):
    full_filename = join_to_project_root(*args)
    if not os.path.exists(full_filename):
        # don't send full error page, as responses generally aren't
        # being seen by human user, but as a component on a page
        print(f"Race resource not found <{full_filename}>")
        return make_response(f"Race resource not found <{full_filename}>", 404)
    return send_file(full_filename)

@blueprint.route("/assets/track/<int:track_id>/img")
@cors_allow_origin
def serve_racetrack_custom_image(track_id):
    track = Racetrack.get_by_id(track_id)
    if track is None:
        abort(404)
    if track.track_image is None or len(track.track_image) == 0 or not track.image_media_type:
        flash("No custom image associated with this track", "danger")
        abort(404)
    ext = re.sub(r'.*/', "", track.image_media_type)
    response = make_response(track.track_image)
    response.headers["Content-type"] = track.image_media_type
    response.headers["Content-disposition"] = f"attachment; filename=racetrack-{track_id}.{ext}"
    response.headers["Content-length"] = len(track.track_image)
    return response

@blueprint.route("/assets/track/<int:track_id>/svg")
@cors_allow_origin
def serve_racetrack_custom_svg(track_id):
    track = Racetrack.get_by_id(track_id)
    if track is None:
        abort(404)
    if track.track_svg is None or len(track.track_svg) == 0:
        flash("No custom SVG path associated with this track", "danger")
        abort(404)
    response = make_response(track.track_svg)
    response.headers["Content-type"] = "image/svg+xml; charset=utf-8"
    response.headers["Content-disposition"] = f"attachment; filename=racetrack-{track_id}.svg"
    response.headers["Content-length"] = len(track.track_svg)
    return response

@blueprint.route("/assets/tracks/<filename>")
@cors_allow_origin
def serve_racetrack_asset(filename):
    return _serve_race_asset_file(
        current_app.config[ConfigSettingNames._RACE_ASSETS_RACETRACK_PATH.name],
        filename
    )

@blueprint.route("/assets/img/<filename>")
@cors_allow_origin
def serve_race_player_image(filename):
    return _serve_race_asset_file(
        current_app.config[ConfigSettingNames._RACE_ASSETS_IMAGES_PATH.name],
        filename
    )

@blueprint.route("/assets/<filename>")
def serve_race_player_asset(filename):
    return _serve_race_asset_file(
        current_app.config[ConfigSettingNames._RACE_ASSETS_PATH.name],
        filename
    )

@blueprint.route("/", strict_slashes=False)
def show_public_races():
    """Race announcement page."""
    next_race=Race.query.filter(
        Race.is_visible==True,
        Race.start_at > datetime.now(timezone.utc)
      ).order_by(Race.start_at.asc()).first()
    races = db.session.query(Race).outerjoin(RaceResult).filter(
            Race.is_visible==True,
            Race.start_at < datetime.now(timezone.utc),
            or_(
                Race.is_abandoned==True,
                and_(
                    RaceResult.race_position > 0,
                    RaceResult.race_position <= 3
                )
            )
        ).order_by(Race.start_at.desc()).all()
    results = [ race.results for race in races ]
    flag_color_css_defs = get_flag_color_css_defs(
        [result for sublist in results for result in sublist]
    )
    return render_template(
        "races/index.html",
        flag_color_css_defs=flag_color_css_defs,
        next_race=next_race,
        races=races,
        replay_anchor=Race.get_replay_anchor(),
    )

@blueprint.route("races.json", strict_slashes=True)
@cors_allow_origin
def serve_races_json():
    filename = get_download_filename("races.json", want_datestamp=True)
    races=Race.query.filter(
        Race.is_visible==True,
        Race.start_at < datetime.now(timezone.utc)
      ).order_by(Race.start_at.asc())
    races_list = [
        {
            "id": race.id,
            "title": race.title,
            "start_at": servertime_str(
                current_app.config[ConfigSettingNames.BUGGY_RACE_SERVER_TIMEZONE.name],
                race.start_at
            ),
            "race_file_url": race.race_file_url if (
                race.is_result_visible and not race.is_abandoned
            ) else None,
            "is_abandoned": race.is_abandoned if race.is_result_visible else None
        }
        for race in races
    ]
    json_data = json.dumps(races_list, indent=1, separators=(',', ': '))
    output = make_response(json_data, 200)
    output.headers["Content-Disposition"] = f"attachment; filename={filename}"
    output.headers["Content-type"] = "application/json"
    output.headers["Content-length"] = len(json_data)
    return output

@blueprint.route("/<int:race_id>/replay")
def replay_race(race_id):
    race = Race.query.filter_by(id=race_id).first_or_404()
    if not (race.is_visible and race.is_result_visible):
        if current_user.is_anonymous or not current_user.is_staff:
            flash("The results of this race are not available yet", "warning")
            abort(403)
    if race.is_abandoned:
        flash("Race was abandoned: nothing to replay", "warning")
        abort(404)
    race_file_url = race.race_file_url
    if race_file_url and not (re.match(r"^https?://", race_file_url)):
        race_file_url = url_for(
            "race.serve_race_player_asset",
            filename=race_file_url
        )
    if player_url := current_app.config[ConfigSettingNames.BUGGY_RACE_PLAYER_URL.name]:
        anchor = Race.get_replay_anchor()
        return redirect(f"{player_url}?race={race_file_url}{anchor}")
    if current_user.is_anonymous:
        current_user_username = "nobody!" # ensure no username match with "!"
    else:
        current_user_username = current_user.username
    return render_template(
        "races/player.html",
        current_user_username=current_user_username,
        cachebuster=current_app.config[ConfigSettings.CACHEBUSTER_KEY],
        race_file_url=race_file_url,
    )

@blueprint.route("/<int:race_id>/result")
def show_race_results(race_id):
    race = Race.query.filter_by(id=race_id).first_or_404()

    if is_preview := not (race.is_visible and race.is_result_visible):
        if current_user.is_anonymous or not current_user.is_staff:
            flash("Results for this race are not available yet", "danger")
            flash("Either the results haven't been uploaded, or they haven't been published yet (maybe try again later?)", "info")
            abort(404)
        else:
            flash("Results for this race have not been published yet: you're seeing this preview because you're staff", "warning")

    all_results = db.session.query(
        RaceResult, User).outerjoin(User).filter(
            RaceResult.race_id==race.id
        ).order_by(RaceResult.race_position.asc()).all() 

    results_finishers = [(res, user)  for (res, user) in all_results if res.race_position > 0 ]
    results_nonfinishers = [(res, user) for (res, user) in all_results if res.race_position == 0 ]
    results_disqualified = [(res, user) for (res, user) in all_results if res.race_position < 0 ]
    is_tied = {}
    prev_pos = 0
    for (res, _) in results_finishers:
        if res.race_position == prev_pos:
            is_tied[prev_pos] = "="
        prev_pos = res.race_position
    flag_color_css_defs = get_flag_color_css_defs([res for (res, _) in all_results])
    return render_template(
        "races/result.html",
        is_preview=is_preview,
        current_user_id=0 if current_user.is_anonymous else current_user.id,
        flag_color_css_defs=flag_color_css_defs,
        is_showing_usernames=current_app.config[ConfigSettingNames.IS_USERNAME_PUBLIC_IN_RESULTS.name],
        is_tied=is_tied,
        race=race,
        replay_anchor=Race.get_replay_anchor(),
        results=all_results,
        results_disqualified=results_disqualified,
        results_finishers=results_finishers,
        results_nonfinishers=results_nonfinishers,
    )

@blueprint.route("/<int:race_id>/race-file.json")
@blueprint.route("/<int:race_id>/race-file")
@cors_allow_origin
def serve_race_file(race_id):
    race = Race.query.filter_by(id=race_id).first_or_404()
    if not (race.is_visible and race.is_result_visible):
        if current_user.is_anonymous or not current_user.is_staff:
            flash("Race file not available yet", "danger")
            abort(403)
    if race.is_abandoned: # don't show race file

buggy_race_server/templates/401.html
{% extends "layout.html" %}
{% block page_title %}Unauthorized{% endblock %}
{% block content %}
<div class="jumbotron text-center">
  <h1 class="display-4">401</h1>
  <p>
    You are not authorized to see this page.
  </p>
  <p>
    Please <a href="{{ url_for('public.login') }}">log in</a>.
  </p>
  <hr class="my-4">
  <p>
    401: <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status">About HTTP status codes</a>
  </p>
</div>
{% endblock %}

buggy_race_server/templates/405.html
{% extends "layout.html" %}
{% block page_title %}Page not found{% endblock %}
{% block content %}
<div class="jumbotron text-center">
  <h1 class="display-4">405</h1>
  <p>
    Method not allowed.
  </p>
  {% if request.method %}
    <p>
      You made a <code>{{ request.method }}</code> request
      for <code>{{ request.path }}</code>.
    </p>
  {% endif %}
  {% if error.valid_methods %}
    <p>
      The only methods allowed here are: 
      <code>{{ ", ".join(error.valid_methods) }}</code>
    </p>
  {% endif %}
  {% if request.path == url_for('api.create_buggy_with_json_via_api') %}
    <p>
      This is why APIs don't just publish the endpoints you should use,
      but also the methods: see
      <a href="{{ url_for('api.describe_api')}}">the Race Server's API specification</a>.
    </p>
  {% endif %}
  <hr class="my-4">
  <p>
    405: <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status">About HTTP status codes</a>
  </p>
</div>
{% endblock %}

buggy_race_server/templates/_local_announcement.html
{# local announcements are only shown on specific pages: e.g., home or login #}
{% if config['_CURRENT_ANNOUNCEMENTS'] %}
  {% for announcement in config['_CURRENT_ANNOUNCEMENTS'] %}
    {% if announcement.type == local_announcement_type %}
      <div class="row">
        <div class="col alert">
          {% if announcement.is_html %}
            {{ announcement.text|safe }}
          {% else %}
            {{ announcement.text }}
          {% endif %}
        </div>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

buggy_race_server/templates/footer.html
<footer>
  {% if not config['_SETUP_STATUS'] %}
    <small>
      <ul class="company">
        <li>
          <a href="{{ config['INSTITUTION_HOME_URL'] }}">{{ config['INSTITUTION_FULL_NAME'] }}</a>
        </li>
        <li>
          Image credits:
          <br>
          Metal plate by <a href="https://www.flickr.com/photos/filterforge/">Filter Forge</a>  CC&nbsp;BY&nbsp;2.0
          <br>
          Illustrations by <a href="http://raulrene.wordpress.com/renes-pixie-pixelarium/">René Carbonell</a> CC&nbsp;BY&nbsp;2.0
        </li>
      </ul>
      <ul class="footer-nav" id="footer-nav">
        <li><a href="{{ url_for('public.home') }}">Home</a></li>
        <li><a href="{{ url_for('public.serve_project_page') }}">Project</a></li>
        {% if config['IS_STORING_STUDENT_TASK_TEXTS'] %}
          <li><a href="{{ url_for('user.list_task_texts') }}">Task texts</a></li>
        {% endif %}
        <li><a href="{{ url_for('user.submit_buggy_data') }}">Upload</a></li>
        <li><a href="{{ url_for('public.show_specs') }}">Specs</a></li>
        <li><a href="{{ url_for('race.show_public_races') }}">Races</a></li>
        <li><a href="{{ url_for('public.about') }}">About</a></li>
        {% if current_user and current_user.is_authenticated %}
            <li><a href="{{ url_for('user.home_page') }}"><span class="icon-home mr-2"></span>{{ current_user.pretty_username }}</a></li>
            {% if current_user.is_staff %}
              <li><a href="{{ url_for('admin.admin') }}"><span class="icon-cog mr-2"></span>Admin</a></li>
            {% endif %}
            <li><a href="{{ url_for('public.logout') }}"><span class="icon-exit mr-2"></span>Logout</a></li>
        {% else %}
          <li><a href="{{ url_for('public.login') }}"><span class="icon-enter mr-2"></span>Log in</a></li>
        {% endif %}

      </ul>
    </small>
  {% endif %}
</footer>

buggy_race_server/templates/layout.html
{% import "admin/macros.html" as macros %}
{% set ns_admin = namespace(is_task_list_out_of_date = None) %}
{% set ns_admin = namespace(is_tech_notes_out_of_date = None) %}
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="{{ static_url_for('static', filename='build/img/favicon.ico') }}">
    <title>
      {% block page_title %} 
      Buggy Race Server
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"/>
    {% block css %}{% endblock %}
    {% if flag_color_css_defs %}
      <style>
        {% for fc in flag_color_css_defs %}.{{ flag_color_css_defs[fc][0] }} {{ flag_color_css_defs[fc][1] }}
        {% endfor %}
      </style>
    {% endif %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %}
      {% with form=form %} 
        {% include "nav.html" %} 
      {% endwith %}
    <header>{% block header %}{% endblock %}</header>
    <main role="main">
      {% if config['_CURRENT_ANNOUNCEMENTS'] %}
        {% for announcement in config['_CURRENT_ANNOUNCEMENTS'] %}
          {% if announcement.type in config['_ANNOUNCEMENT_TOP_OF_PAGE_TYPES'] %}
            <div class="row my-2 mx-0 announcement-wrapper announcement-{{ announcement.type }} w-100">
              <div class="announcement-inner-box text-center alert">
                  {% if announcement.is_html and not request.url.endswith('/no-html') %}
                    {{ announcement.text|safe }}
                  {% else %}
                    {{ announcement.text }}
                  {% endif %}
              </div>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
      <div id="flash-msgs">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            <div class="my-3">
              {% for category, message in messages %}
                <div class="row alert alert-{{ category }} my-2 {%if message.startswith('Authorisation code') or message.startswith('Auth code')%}bad-auth{% endif %}">
                  <div class="container">
                    <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                    {{ message }}
                  </div>
                </div>
              {% endfor %}
            </div>
          {% endif %}
        {% endwith %}
      </div>
      <div class="m-1" id="main-content-block">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "footer.html" %}
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    {% endblock %}
  </body>
</html>

buggy_race_server/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
     {% if config["_IS_DEMO_SERVER"] %}
       <span style="color:orange">Demo</span>
     {% endif %}
     Race Server 
  </a>
  {% if config['_SETUP_STATUS'] %}
    <ul class="navbar-nav mr-auto">
      <li><a href="{{ url_for('admin.setup') }}" class="btn btn-small btn-warning">Setting up...</a></li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {% if current_user and current_user.is_authenticated %}ghosted{% endif %}" href="{{ url_for('public.login') }}"><span class="icon-enter mr-2"></span>Log&nbsp;in</a>
      </li>
    </ul>
  {% else %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('public.serve_project_page') }}">Project</a>
        </li>
        {% if config['IS_STORING_STUDENT_TASK_TEXTS'] %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.list_task_texts') }}">Texts</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.submit_buggy_data') }}">Upload</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{{ url_for('public.show_specs') }}">Specs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('race.show_public_races') }}">Races</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
        </li>
      </ul>
      {% if current_user and current_user.is_authenticated %}
        <ul class="navbar-nav">
          {% if current_user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.admin') }}"><span class="icon-cog mr-2"></span>Admin</a>
            </li>
          {% endif %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('user.home_page') }}"><span class="icon-home mr-2"></span>Logged in as {{ current_user.pretty_username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('public.logout') }}"><span class="icon-exit mr-2"></span>Log&nbsp;out</a>
          </li>
        </ul>
      {% else %} 
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('public.login') }}"><span class="icon-enter mr-2"></span>Log&nbsp;in</a>
          </li>
        </ul>
      {% endif %}
    </div>
  {% endif %}
</nav>