buggy_race_server/api/views.py
# -*- coding: utf-8 -*-
"""API views."""

import json
from datetime import datetime, timezone, timedelta

from flask import Blueprint, Response, request, current_app, render_template, after_this_request

from buggy_race_server.buggy.forms import BuggyJsonForm
from buggy_race_server.buggy.views import handle_uploaded_json
from buggy_race_server.user.models import User
from buggy_race_server.config import ConfigSettingNames
from buggy_race_server.admin.views import get_admin_dashboard_data_response

blueprint = Blueprint("api", __name__, url_prefix="/api", static_folder="../static")

API_SECRET_LIFESPAN_MINS = 60

API_KEY_USER = "user"
API_KEY_KEY = "key" # API key for the API key, heh
API_KEY_SECRET = "secret"
API_KEY_JSON = "buggy_json"

def get_json_error_response(msg, status=401):
  response = Response(
    '{"error": "' + msg + '"}',
    status=status,
    mimetype="application/json"
  )
  response.headers.add("Access-Control-Allow-Origin", "*") # CORS
  return response

@blueprint.route("/", methods=["GET"], strict_slashes=False)
def describe_api():
  return render_template(
    "public/api.html",
    api_task_name=current_app.config[ConfigSettingNames.TASK_NAME_FOR_API.name],
    buggy_race_server_url=current_app.config[ConfigSettingNames.BUGGY_RACE_SERVER_URL.name],
  )

def get_user_or_response_from_api_post(request):
    """ returns either"""
    username = ""
    api_key = ""
    secret = ""
    if API_KEY_USER in request.form:
        username = request.form[API_KEY_USER].strip()
    if not username:
        return get_json_error_response("missing user")
    if API_KEY_KEY in request.form:
        api_key = request.form[API_KEY_KEY].strip()
    if not api_key:
        return get_json_error_response("missing API key")
    if API_KEY_SECRET in request.form:
        secret = request.form[API_KEY_SECRET].strip()
    if not secret:
        return get_json_error_response("missing secret")
    user = User.query.filter_by(username=username).first()
    if user is None:
        return get_json_error_response("not authorised (bad user)")
    if user.api_key != api_key:
        return get_json_error_response("not authorised (wrong API key for this user)")
    if user.api_secret is None:
        return get_json_error_response("not authorised (missing secret)")
    if user.api_secret_at is None:
        return get_json_error_response("not authorised (missing secret timestamp)")
    if user.api_secret != secret:
        return get_json_error_response(f"not authorised (bad secret)")
    now_utc = datetime.now(timezone.utc)
    api_secret_at_utc = user.api_secret_at.replace(tzinfo=timezone.utc)
    try:
        delta_time_in_s = (now_utc - user.api_secret_at) / timedelta(seconds=1)
    except TypeError:
        delta_time_in_s = (now_utc - api_secret_at_utc) / timedelta(seconds=1)
    if delta_time_in_s > current_app.config[ConfigSettingNames.API_SECRET_TIME_TO_LIVE.name]:
        return get_json_error_response("not authorised (secret has expired)")
    if user.is_api_secret_otp:
        if user.api_secret_count > 0:
            return get_json_error_response("one-time secret has already been used")
        user.api_secret_count += 1
        user.save()
    return user

@blueprint.route("/upload", methods=["POST", "OPTIONS"], strict_slashes=True)
def create_buggy_with_json_via_api():
  """ API call  """
  # basic API call to /api/upload with four params:
  #        user (the username for the user whose buggy to use)
  #        key (the API key for this user)
  #        secret (must match recent secret)
  #        buggy_json
  #
  if request.method == "OPTIONS":
      # CORS preflight enquiry
      # wildcards are OK here because the API is stateless so isn't
      # handling cookies: auth is provided in the data payload
      response = Response(status=204) # 204: no content
      response.headers.add("Access-Control-Allow-Origin", "*")
      response.headers.add("Access-Control-Allow-Headers", "*")
      response.headers.add("Access-Control-Allow-Methods", "POST")
      return response
  user_or_response = get_user_or_response_from_api_post(request)
  if isinstance(user_or_response, Response):
      return user_or_response
  if not isinstance(user_or_response, User): # unexpected: should be Resonse or User
      return get_json_error_response("bad request") # didn't get a user
  user = user_or_response
  if API_KEY_JSON in request.form:
      buggy_json = request.form[API_KEY_JSON].strip()
  if not buggy_json:
      return get_json_error_response(f"no JSON ({API_KEY_JSON}) provided", status=200)
  # now send 200 even when response is an error (e.g., JSON parse fail)
  response = Response(
    json.dumps(handle_uploaded_json(BuggyJsonForm(request.form), user, True)),
    status=200,
    mimetype="application/json"
  )
  response.headers.add("Access-Control-Allow-Origin", "*") # CORS
  return response

@blueprint.route("/admin/dashboard", methods=["GET", "POST"], strict_slashes=True)
def dashboard_data_via_api():
    """ API call  """
    @after_this_request
    def add_no_cache_header(response):
        # discourage caching here
        response.headers["Vary"] = "*" # Flask also unhelpfully sets "cookie"
        response.headers["Cache-Control"] = "no-cache"
        return response
    payload = {}
    if not current_app.config[ConfigSettingNames.IS_ADMIN_API_ENABLED.name]:
        status = 404
    elif request.method != "POST":
        status = 405 # method not allowed
    else:
        user_or_response = get_user_or_response_from_api_post(request)
        if isinstance(user_or_response, Response):
            return user_or_response
        user = user_or_response
        if not user.is_administrator:
            return get_json_error_response("not authorised (user not an administrator)")
        return get_admin_dashboard_data_response(want_json=True)
    return Response(
        json.dumps(payload) if payload else None, # None results in empty body
        status=status,
        mimetype="application/json"
    )

buggy_race_server/oauth/views.py
# -*- coding: utf-8 -*-
"""Oauth Routes"""

from flask import Blueprint, redirect, request, url_for, current_app
from flask_login import login_required, current_user
from buggy_race_server.lib.http import Http, Url

blueprint = Blueprint("oauth", __name__, url_prefix="/oauth")

http = Http({
    'Content-Type': 'application/json',
    'Accept': 'application/json'
})

@blueprint.route('/github')
@login_required
def github():
    """Redirect to github login url"""
    # TODO: Add state to prevent CORS attacks
    return redirect(str(Url.of('https://github.com/login/oauth/authorize', {
        'client_id': current_app.config['GITHUB_CLIENT_ID'],
        'redirect_uri': url_for('oauth.github_callback', _external=True),
        'allow_signup': 'true',
        'scope': 'user repo'
    })))

@blueprint.route('/github/callback')
@login_required
def github_callback():
    code = request.args.get('code')

    # TODO: Add state here too
    response = http.post('https://github.com/login/oauth/access_token', {}, {
        'client_id': current_app.config['GITHUB_CLIENT_ID'],
        'client_secret': current_app.config['GITHUB_CLIENT_SECRET'],
        'code': code,
        'redirect_uri': url_for('oauth.github_callback', _external=True)
    })

    current_user.github_access_token = response.json()['access_token']
    current_user.github_username = current_user.github.get('/user').json()['login']
    current_user.save()

    return redirect(url_for('user.home_page'))

buggy_race_server/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

buggy_race_server/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
import time
from datetime import datetime, timezone
import threading
import markdown
from markupsafe import Markup
from flask import (
    abort,
    Blueprint,
    current_app,
    flash,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    Response,
    url_for,
)
from flask_login import login_required, current_user
from functools import wraps
from wtforms import ValidationError

from buggy_race_server.admin.forms import TaskTextForm, TaskTextDeleteForm
from buggy_race_server.admin.models import TaskText, Task
from buggy_race_server.buggy.forms import BuggyJsonForm
from buggy_race_server.config import AnnouncementTypes, ConfigSettings, ConfigSettingNames
from buggy_race_server.lib.issues import IssueParser
from buggy_race_server.user.models import User
from buggy_race_server.user.forms import ChangePasswordForm, ApiSecretForm
from buggy_race_server.utils import (
    active_user_required,
    join_to_project_root,
    flash_errors,
    get_download_filename,
    get_pretty_approx_duration,
    get_user_task_texts_as_list,
    is_authorised,
    is_poster,
    warn_if_insecure,
)

blueprint = Blueprint("user", __name__, url_prefix="/user", static_folder="../static")

DELAY_BEFORE_INJECTING_ISSUES = 30 # give repo generous time to get issue auth before starting

def flash_explanation_if_unauth(msg):
    """Improve a 403 by explaining what it is you could do if you were logged in"""
    def decorator(function):
        @wraps(function)
        def decorated_function(*args, **kwargs):
            if not (current_user.is_authenticated and current_user.is_active):
                if msg: flash(msg, "warning")
            return function(*args, **kwargs)
        return decorated_function
    return decorator

# 
@blueprint.route("/home", strict_slashes=False)
@flash_explanation_if_unauth("You must log in before you can access your home page and settings")
@login_required
@active_user_required
def home_page():
    form = ChangePasswordForm()
    is_student_using_vcs = (
        current_app.config[ConfigSettingNames.IS_USING_VCS.name]
        and current_app.config[ConfigSettingNames.IS_STUDENT_USING_REPO.name]
    )
    is_using_vcs_to_fork = (
        current_app.config[ConfigSettingNames.IS_USING_VCS.name]
        and current_app.config[ConfigSettingNames.IS_USING_GITHUB_API_TO_FORK.name]
    )
    report_type = current_app.config[ConfigSettingNames.PROJECT_REPORT_TYPE.name]
    is_report = bool(report_type) # if it's not empty string (or maybe None?)
    poster_type = current_app.config[ConfigSettingNames.PROJECT_POSTER_TYPE.name]
    is_a_poster = is_poster(current_app)
    if is_report:
        report_link_text = "Report"
        if is_a_poster:
            report_link_text = "Report & Poster"
    elif is_a_poster:
        report_link_text = "Poster"
    else:
        report_link_text = ""
    return render_template(
        "user/home.html",
        form=form,
        ext_id_name=current_app.config[ConfigSettingNames.EXT_ID_NAME.name],
        ext_username_name=current_app.config[ConfigSettingNames.EXT_USERNAME_NAME.name],
        is_poster=is_a_poster,
        is_report=is_report,
        is_secure=request.is_secure or not current_app.config[ConfigSettingNames._IS_REQUEST_TLS_EXPECTED.name],
        is_showing_tech_notes=current_app.config[ConfigSettingNames.IS_SHOWING_TECH_NOTES.name],
        is_showing_workflow=current_app.config[ConfigSettingNames.IS_SHOWING_PROJECT_WORKFLOW.name],
        is_storing_student_task_texts=current_app.config[ConfigSettingNames.IS_STORING_STUDENT_TASK_TEXTS.name],
        is_storing_texts=current_app.config[ConfigSettingNames.IS_STORING_STUDENT_TASK_TEXTS.name],
        is_student_using_vcs=is_student_using_vcs,
        is_using_vcs_to_fork=is_using_vcs_to_fork,
        report_link_text=report_link_text,
        report_type=current_app.config[ConfigSettingNames.PROJECT_REPORT_TYPE.name],
        server_url=current_app.config[ConfigSettingNames.BUGGY_RACE_SERVER_URL.name],
        submission_link=current_app.config[ConfigSettingNames.PROJECT_SUBMISSION_LINK.name],
        users_have_email=current_app.config[ConfigSettingNames.USERS_HAVE_EMAIL.name],
        users_have_ext_id=current_app.config[ConfigSettingNames.USERS_HAVE_EXT_ID.name],
        users_have_ext_username=current_app.config[ConfigSettingNames.USERS_HAVE_EXT_USERNAME.name],
        users_have_first_name=current_app.config[ConfigSettingNames.USERS_HAVE_FIRST_NAME.name],
        users_have_last_name=current_app.config[ConfigSettingNames.USERS_HAVE_LAST_NAME.name],
        vcs_name=current_app.config[ConfigSettingNames.VCS_NAME.name],
    )

@blueprint.route("/new")
def register_new_user():
    if not current_app.config[ConfigSettingNames.IS_PUBLIC_REGISTRATION_ALLOWED.name]:
        flash(
          "You must be logged in as an administrator to register new users "
          "(public registration is not enabled)", "warning"
        )
        abort(403)
    return redirect(url_for('admin.new_user'))

@blueprint.route("/upload", strict_slashes=False)
@flash_explanation_if_unauth("You must log in before you can upload data for your buggy ")
@login_required
@active_user_required
def submit_buggy_data():
    """Submit the JSON for the buggy."""
    if (
        current_app.config[ConfigSettingNames.IS_USING_VCS.name]
        and
        current_app.config[ConfigSettingNames.IS_USING_GITHUB_API_TO_FORK.name]
        and
        not current_user.is_github_connected()
    ):
        vcs_name = current_app.config[ConfigSettingNames.VCS_NAME.name]
        flash(
            Markup(
                f"You haven't connected to {vcs_name} yet. "
                f"<a href='{url_for('user.home_page')}'>Do it now!</a>"
            ),
            "danger"
        )
    return render_template(
        "user/submit_buggy_data.html",
        form=BuggyJsonForm(request.form)
    )

@blueprint.route('/setup-course-repository', methods=['POST'], strict_slashes=False)
@login_required
@active_user_required
def setup_course_repository():
    """Create a new fork of the BUGGY_EDITOR_REPO if one doesn't already exist"""
    if current_user.has_course_repository():
        flash("Didn't try to fork: it looks like there's already a repo there", "danger")
        return redirect(url_for('user.home_page'))

    # Forking is async so we assume we're successful and hope for the best!
    repo = current_user.github.post(
        f"/repos/{current_app.config[ConfigSettingNames.BUGGY_EDITOR_REPO_OWNER.name]}"
        f"/{current_app.config[ConfigSettingNames.BUGGY_EDITOR_REPO_NAME.name]}/forks")

    # Forks don't get issues by default
    current_user.github.patch(
        f"/repos/{current_user.github_username}/{current_app.config[ConfigSettingNames.BUGGY_EDITOR_REPO_NAME.name]}",
        {},
        { 'has_issues': 'true'}
    )

    # this could probably be cached?
    # needs to run in current app context (same thread)
    issues_parser = IssueParser(
        join_to_project_root(
          current_app.config[ConfigSettingNames._PUBLISHED_PATH.name],
          current_app.config[ConfigSettingNames._BUGGY_EDITOR_ISSUES_CSV_FILE.name]
        ),
        current_app.config[ConfigSettingNames.BUGGY_EDITOR_ISSUES_CSV_HEADER_ROW.name]
    )

    def inject_issues_into_repo(user, repo_name, issues_parser):
        # passing arguments to avoid dependency on app context (this runs in another thread)
        #
        # CONTEXT ONY: ---Issues appear in most recent order and we want the first task
        # to appear as the most recent issue!---
        #
        # Except then when the github api rate limits us, the first issues
        # don't get delivered :(
        for i, issue in enumerate(issues_parser.parse_issues()):
            response = user.github.post(
                f"/repos/{user.github_username}/{repo_name}/issues",
                {},
                {
                    'title': issue['title'],
                    'body': issue['body'],
                    'assignees': [user.github_username]
                }
            )

            # We were trigger abuse stuff from github so go slowly!
            # See here: https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-abuse-rate-limits
            time.sleep(2.0)

    # delay here in case the has_issues patch is taking a while to authenticate...
    # since the repo is always being made but the first 1d6 issues aren't making it
    #
    # Note: inject_issues_into_repo must will run _without_ an app context
    threading.Timer(
        DELAY_BEFORE_INJECTING_ISSUES,
        inject_issues_into_repo,
        args=[
          current_user._get_current_object(),
          current_app.config[ConfigSettingNames.BUGGY_EDITOR_REPO_NAME.name],
          issues_parser,
        ]
    ).start()

    return redirect(url_for('user.home_page'))

@blueprint.route("/password/<username>", methods=['GET'], strict_slashes=False)
@blueprint.route("/password", methods=['GET','POST'], strict_slashes=False)
@login_required
@active_user_required
def change_password(username=None):
    """Change user's password (staff may be able to change another user's password)."""
    warn_if_insecure()
    form = ChangePasswordForm(request.form)
    is_ta_password_change_enabled = current_app.config[ConfigSettingNames.IS_TA_PASSWORD_CHANGE_ENABLED.name]
    users_pw_can_be_changed = []
    admin_usernames = []
    if (current_user.is_administrator 
        or
        (current_user.is_teaching_assistant and is_ta_password_change_enabled)
    ):
        users = User.query.filter(User.is_active==True).all()
        if not current_user.is_administrator:
            users = [user for user in users if not user.is_staff]
        users_pw_can_be_changed = [user.username for user in users]
        admin_usernames = [user.username for user in users if user.is_administrator]
    if request.method == "POST":

buggy_race_server/templates/user/home.html
{% extends "layout.html" %}
{% block page_title %} {{ current_user.pretty_username }} home {% endblock %}
{% block content %}

<div class="container pb-5">

  <div class="row">
    <h1 class="col my-3">
      <span class="icon-home mr-2"></span>{{ current_user.pretty_username }}
      on the race server
    </h1>
  </div>

  <div class="row">
    <div class="col-lg">
      <div class="row">
        <div class="col-md">
          <div class="alert alert-info">
            <h2 class="alert-title">Your race server account</h2>
            <p class="btn-collection">
              <a href="{{ url_for('user.change_password') }}" class="btn btn-outline-secondary btn-white btn-jump">Change password</a>
              <a href="{{ url_for('user.set_api_secret') }}" class="btn btn-outline-secondary btn-white btn-jump">Set&nbsp;API&nbsp;secret</a>
              {% if is_storing_student_task_texts %}
                <a href="{{ url_for('user.list_task_texts') }}" class="btn btn-outline-secondary btn-white btn-jump">List&nbsp;your&nbsp;task&nbsp;texts</a>
              {% endif %}
            </p>
          </div>
        </div>
        {# don't show user details if the _only_ details are: "you are a student" #}
        {% 
          if (not current_user.is_student or not current_user.is_active) or
          (users_have_first_name or users_have_last_name or users_have_ext_username or users_have_ext_id or users_have_email)
        %}
          <div class="col-md">
            <table class="col table table-striped table-bordered table-hover bg-white">
              <tbody>
                <tr>
                  <td>Username</td>
                  <td><code>{{ current_user.username }}</code></td>
                </tr>
                <tr>
                  <td>Student?</td>
                  <td class="{% if current_user.is_student %}alert-success{% endif %}">
                    {% if current_user.is_student %}
                      Yes
                    {% else %}
                      No
                    {% endif %}
                    </td>
                </tr>
                {% if current_user.is_staff %}
                  <tr>
                    <td>Staff?</td>
                    <td>
                      Yes:
                      {% if current_user.is_administrator %}
                        &starf; administrator
                      {% elif current_user.is_teaching_assistant %}
                        &star; teaching assistant
                      {% else %}
                        <em>unknown</em>
                      {% endif %}
                      <p class="btn-collection">
                        <a href="{{ url_for('admin.admin') }}" class="btn btn-outline-secondary btn-admin btn-jump"><span class="icon-cog"></span> Admin&nbsp;pages</a>
                      </p>
                      {% if current_user.is_administrator %}
                        <div id="is-admin-always-expanded-container" class="form-group mt-3 hidden">
                          <label for="is-admin-always-expanded">Admin button preference:</label>
                          <select name="is-admin-always-expanded" id="is-admin-always-expanded" class="form-control mr-sm-1">
                            <option value="1" selected>Expanded</option>
                            <option value="0">Collapsed</option>
                          </select>
                        </div>
                      {% endif %}
                    </td>
                  </tr>
                {% endif %}
                {% if not current_user.is_active %}
                  {# probably shouldn't/can't be logged in #}
                  <tr>
                    <td>Active?</td>
                    <td class="alert-danger">No</td>
                  </tr>
                {% endif %}
                {% if users_have_first_name or users_have_last_name %}
                <tr>
                  <td>
                    {% if not users_have_first_name %}
                      Last name
                    {% else %}
                      Name
                    {% endif %}
                  </td>
                  <td>
                    {% if current_user.full_name is none %}
                      <em class="empty-setting">none</em>
                    {% else %}
                      {{ current_user.full_name }}
                    {% endif %}
                  </td>
                </tr>
                {% endif %}
                {% if users_have_email %}
                  <tr>
                    <td>Email</td>
                    <td>
                      {% if current_user.email is none %}
                        <em class="empty-setting">none</em>
                      {% else %}
                        {{ current_user.email }}
                      {% endif %}
                    </td>
                  </tr>
                {% endif %}
                {% if users_have_ext_username %}
                  <tr>
                    <td>{{ ext_username_name }}</td>
                    <td>
                      {% if current_user.ext_username is none %}
                        <em class="empty-setting">none</em>
                      {% else %}
                        {{ current_user.ext_username }}
                      {% endif %}
                    </td>
                  </tr>
                {% endif %}
                {% if users_have_ext_id %}
                  <tr>
                    <td>{{ ext_id_name }}</td>
                    <td>
                      {% if current_user.ext_id is none %}
                        <em class="empty-setting">none</em>
                      {% else %}
                        {{ current_user.ext_id }}
                      {% endif %}
                    </td>
                  </tr>
                {% endif %}
              </tbody>
            </table>
          </div>
        {% endif %}
      </div>
    </div>
    {% if is_using_vcs_to_fork %}
      <div class="col-lg">
        <div class="alert border-secondary">
          <h2 class="alert-title">Your {{ vcs_name }} account</h2>
          {# an increasingly urgent bodge: don't allow insecure unless dev on local:   #}
          {% if not is_secure %}
            <div class="alert alert-danger">
              <h2 class="alert-title">Warning: You are not using the secure race server!</h2>
              <p>
                Accessing up your {{ vcs_name }} account won't work unless
                you're logged into the secure server.
              </p>
              {% if server_url.startswith("https:") %}
                <p>
                  <a href="{{ server_url }}" class="btn btn-warning btn-jump">Switch to {{ server_url }}</a>
                </p>
              {% endif %}
            </div>
          {% else %}
            {% if current_user.is_github_connected() %}
              <div class="alert alert-warning">
                This buggy racing account is connected to your {{ vcs_name }} account
                (<strong>{{ current_user.github_username }}</strong>).
              </div>
              {% if current_user.has_course_repository() %}
                <p>
                  You have forked the Buggy Editor repo into your {{ vcs_name }} account.
                </p>
                <p class="btn-collection">
                  <a href="{{ current_user.course_repository }}" class="btn btn-outline-primary btn-white btn-jump">Your {{ vcs_name }} repo</a>
                </p>
                {% if is_using_vs_workspace %}
                  <div class="alert alert-info my-3">
                    <h2 class="alert-title">VS Code workspace</h2>
                    <p>
                      This workspace file connections your Visual Studio Code application to
                      your account on {{ project_remote_server_name or "the remote server" }}.
                      Download your VScode workspace file and load it into VS Code.
                      <!-- TODO ...and some instruction! -->
                    </p>
                    <p class="btn-collection">
                      <a href="{{ url_for('user.download_vscode_workspace') }}" class="btn btn-primary btn-download">Download VS&nbsp;Code workspace</a>
                    </p>
                  </div>
                {% endif %}
                {% include "_local_announcement.html" %}
              {% else %}
                <div class="alert alert-primary">
                  <p>
                    You can now <em>fork</em> the Buggy Editor repo.
                    This will copy all the files you need into your own
                    {{ vcs_name }} account
                    (<strong>{{ current_user.github_username }}</strong>).
                    It will also add the project tasks as <em>issues</em>
                    to that repo.
                  </p>
                  <div class="my-3">
                    <form action="{{ url_for('user.setup_course_repository') }}" method="POST">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                      <button type="submit" class="btn btn-primary btn-jump">Fork Buggy Editor repo</button>
                    </form>
                  </div>
                  <p>
                    Forking may take a few moments, so be patient when you click the button.
                  </p>
                </div>
              {% endif %}
            {% else %}
              <p>
                If you connect your {{ vcs_name }} account to this buggy racing
                server, we'll fork the Buggy Editor repo into your
                own account and then add the project tasks (as {{ vcs_name }}
                "issues").
              </p>
              <p class="alert alert-danger">
                To do this, this buggy racing server needs access to the 
                <strong>repositories</strong> and <strong>personal user
                data</strong> of your {{ vcs_name }} account. When you click on
                the button below, {{ vcs_name }} will ask you to confirm that
                you know this server needs such access.
              </p>
              <p>
                If you don't have a {{ vcs_name }} account yet, you can create
                one as part of the process when you click this button (although
                it's simpler if you are already logged into {{ vcs_name }}
                before you start).
              </p>
              <p class="my-3">
                <a href="{{ url_for('oauth.github') }}" class="btn btn-primary btn-jump">Connect your {{ vcs_name }} account</a>
              </p>
              <p>
                Afterwards, expect to receive an email from {{ vcs_name }}
                alerting you that “a third-party OAuth application
                ({{ config['INSTITUTION_SHORT_NAME']}} Buggy Racing Server)
                with repo and user scopes was recently authorized to access
                your account.”
              </p>
            {% endif %}
          {% endif %}
        </div>
      </div>
    {% endif %}
  </div>

  <div class="row">
    <div class="col">
      <div class="alert alert-success">
        <h2 class="alert-title">Buggy pitstop</h2>
        <p class="btn-collection">
          <a href="{{ url_for( 'user.submit_buggy_data' ) }}" class="btn btn-outline-secondary btn-white btn-jump"><span class="icon-wrench mr-2"></span>Upload&nbsp;JSON</a>
          <a href="{{ url_for( 'buggy.show_own_buggy' ) }}" class="btn btn-outline-secondary btn-white btn-jump">View&nbsp;buggy</a>
          <a href="{{ url_for( 'public.show_specs' ) }}" class="btn btn-outline-secondary btn-white btn-jump">Race&nbsp;specs</a>
        </p>
      </div>
    </div>
    {% if is_student_using_vcs %}
      <div class="col">
        <div class="alert alert-warning">
          <h2 class="alert-title">Your {{ vcs_name }} account</h2>
          <p>
            <a href="{{ current_user.editor_repo_url }}" title="buggy repo"
              class="btn btn-outline-secondary btn-white btn-sm btn-jump ml-1">Repo</a>
          </p>
        </div>
      </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col">
      <div class="alert border-secondary">
        <h2 class="alert-title">Project links</h2>
        <p class="btn-collection">
          <a class="btn btn-outline-secondary btn-white btn-jump" href="{{ url_for( 'public.serve_project_page' ) }}">About the project</a>
          {% if is_showing_workflow %}
            <a class="btn btn-outline-secondary btn-white btn-jump" href="{{ workflow_url or url_for('public.serve_project_page', page='workflow') }}">Workflow</a>
          {% endif %}
          {% if submission_link %}
            <a href="{{ submission_link }}" class="btn btn-outline-secondary btn-white btn-jump">Submission</a>
          {% endif %}
        </p>
        {% include "public/project/_project_links.html" %}
      </div>
    </div>
  </div>

</div>
{% endblock %}

buggy_race_server/templates/user/notes.html
{% extends "layout.html" %}
{% block content %}
<div class="container pb-5">
  <div class="row">
    <h1 class="col my-3">
      {% if is_own_note %}
          Your
      {% else %}
          {{ user.pretty_username }}'s
      {% endif %}
      {{ report_type }} task notes
    </h1>
  </div>
  {% include "admin/_task_notes_for_user.html" %}
  <div class="row mt-5">
    <div class="col btn-collection">
      <a href="{{ url_for('public.serve_project_page', page='tasks') }}" class="btn btn-outline-secondary">Task list &rtri;</a>
      {% if report_type %}
        <a class="btn btn-outline-secondary" href="{{ url_for( 'public.serve_project_page', page=report_type ) }}">{{ report_type | title }} details &rtri;</a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}